### PR TITLE
WIP: Pod exec

### PR DESCRIPTION
**Pull request by alexgleason**
This builds off @bradleyd's #68 MR, with develop merged back into it, and adds the `K8s.Client.exec` delegate.

I haven't tested if it works yet.

### CODE REVIEW

**Comment by aleDsz** [comment]
Hey @alexgleason, awesome work!

What's the next steps to make this work? Would you like some help if you don't have free time?

**Comment by alexgleason** [comment]
I forgot that I even did this.

I ended up running c37d3acb99b0483473b495a9b9f25111cae57042 in production (that's @bradleyd's commit) and it worked great.

**Comment by aleDsz** [comment]
But since we had some changes on develop branch, I could help to make it work with new API and then we can ship this PR.

WDYT?

**Comment by icehaunter** [comment]
Anything I can do to assist with this? I'm missing this functionality and would be happy to help.

**Comment by mruoss** [comment]
Help would be welcome. The steps I see for this to be ready to be merged:

- [ ] rebase the branch
- [ ] fix the pipeline
- [ ] add integration test(s)
- [ ] Add CHANGELOG.md entry

**Comment by bradleyd** [comment]
I picked up my old branch and rebased with upstream develop. There are some changes :)
I am working through the issues and hope to have a working branch again very soon.

**Comment by bradleyd** [comment]
OK, I merged develop back into my old branch. I fixed all the interface changes that I could see and to make the tests pass. Here is the new PR https://github.com/coryodaniel/k8s/pull/190

**Pull request closed without merging**
