### PR TITLE
Not valid JSON in response

### PR DESCRIPTION
**Pull request by mruoss**
Some weird behaviour was reported here: https://github.com/coryodaniel/k8s/issues/48#issuecomment-1386910670

Adding a reliability test to verify.
---

#### Requirements for all pull requests

- [x] Entry in CHANGELOG.md was created

#### Additional requirements for new features

- [ ] New unit tests were created
- [ ] New integration tests were created
- [ ] PR description contains a link to the according kubernetes documentation

### CODE REVIEW

**Comment by mruoss** [comment]
@arathunku

I've added a new test but I can't get it to fail locally... let's see on CI.

**Comment by arathunku** [comment]
@mruoss that's quick! On CI, is this using ssl, serviceaccount and token auth too? Just in case it doesn't fail, I'm thinking what else might be different.

**Comment by mruoss** [comment]
> On CI, is this using ssl, serviceaccount and token auth too?

Okay I see... I don't think it does...

**Comment by arathunku** [comment]
My `Conn` looks exactly like below (some data stubbed)

```sh
{:ok,
 %K8s.Conn{
   cluster_name: nil,
   user_name: nil,
   url: "https://kubernetes.default.svc",
   insecure_skip_tls_verify: false,
   ca_cert: <<48, .....>>,
   auth: K8s.Conn.Auth.Token<...>,
   middleware: %K8s.Middleware.Stack{
     request: [K8s.Middleware.Request.Initialize,
      K8s.Middleware.Request.EncodeBody],
     response: []
   },
   discovery_driver: K8s.Discovery.Driver.HTTP,
   discovery_opts: [],
   http_provider: SpotUpkill.K8s.HTTPProvider, # switched, working
   cacertfile: "/usr/src/app/_build/prod/lib/castore/priv/cacerts.pem"
 }}
````

**Comment by mruoss** [comment]
ok that was not it. same result locally with token based auth:

```elixir
%K8s.Conn{
  cluster_name: "k3d-k8s-ex",
  user_name: "k3d-k8s-ex-admin",
  url: "https://0.0.0.0:53225",
  insecure_skip_tls_verify: true,
  ca_cert: <<48, ...>>,
  auth: K8s.Conn.Auth.Token<...>,
  middleware: %K8s.Middleware.Stack{
    request: [K8s.Middleware.Request.Initialize,
     K8s.Middleware.Request.EncodeBody],
    response: []
  },
  discovery_driver: K8s.Discovery.Driver.HTTP,
  discovery_opts: [],
  http_provider: K8s.Client.MintHTTPProvider,
  cacertfile: "/etc/ssl/cert.pem"
}

```

**Comment by mruoss** [comment]
What's your cluster version?

**Comment by mruoss** [comment]
Okay, I was able to reproduce the faulty behaviour on a newer cluster (v1.25.2). I actually found a bug in my implementation. @arathunku can you test again with this branch?

**Comment by arathunku** [comment]
It's exactly: `v1.24.7` @ EKS

I've tested the branch, it works! No more errors.

```
iex> (0..50) |> Enum.map(fn _ -> SpotUpkill.K8s.list_spot_nodes() end) |> Enum.all?(&match?({:ok, %{}}, &1))
true
```

Absolutely amazing @mruoss, thank you

**Comment by mruoss** [comment]
Thanks again for your help!

**Pull request merged**
